### ISSUE TITLE
Add multiple backups for input

### ISSUE THREAD

**Issue by skhalymon** [ALLATRA-IT/ephyr#208]
Allow to do smth like
![image](https://user-images.githubusercontent.com/1163493/186258457-48e4c249-ae41-4522-a028-25a7fd7870dd.png)

**Comment by deiwo** [comment]
I wanted to do something like this a while back, it would also make the file backup implementation more straightforward.

**Comment by deiwo** [comment]
Well this a huge change, especially to all ffmpeg related stuff and to some mutations in state.rs, so I would do it separately.

**Comment by skhalymon** [comment]
Connected with #89
