### ISSUE TITLE
Add "Start All" / "Stop All" buttons on dashboard

### ISSUE THREAD

**Issue by PavelKushnirchuk** [ALLATRA-IT/ephyr#241]
We need ability to start / stop all outputs of all clients on dashboard. 
So let's add buttons "Start All" / "Stop All"  below output filters

**Comment by skhalymon** [comment]
Need to implement https://github.com/ALLATRA-IT/ephyr/issues/162 to work this feature under Password

**Comment by skhalymon** [comment]
Closed in #296
