### ISSUE TITLE
Update options on separate page for output

### ISSUE THREAD

**Issue by skhalymon** [ALLATRA-IT/ephyr#54]
On separate output page need to update:
- [ ] Allow to access without password even if password is set. It's secure because URL contain UUID which is impossible to guess.
- [ ] If the user is not logged, hide `close`, `edit` and back to main screen page possibilities (probably start\stop as well). Basically the user should be able only to change volume of the stream.

**Comment by iAnanich** [comment]
it would be great to indicate the stream status and status of output streams that originate from the current output. It can be done by either allowing user (on the main page) to optionally input not the whole URL but just select from one of the inputs on this very same Ephyr instance. Or by searching among available outputs on the current Ephyr instance.
For outputs, "connected" in such way, their label and status must be displayed.

**Comment by iAnanich** [comment]
> Basically the user should be able only to change volume of the stream.
... and delay. But the delay UI has to be changed (timeout for applying changes and/or "apply" button) to prevent rapid re-connections.
