### ISSUE TITLE
Input remains active when deleted

### ISSUE THREAD

**Issue by digest0r** [ALLATRA-IT/ephyr#59]
Little bug:
- When you have active stream to some input
- And you delete the input
- Then the stream in your streaming software continues, but it should be cut off. It creates inconsistencies (you can create new input with the same URL)

Description of bug: https://1drv.ms/v/s!ApvodEdSAQ7goHgCkwGflkqYfTF4?e=9K9W0R

**Comment by deiwo** [comment]
This was related to problem #37 where reqwest package is using Tokio1.x and others are using 0.2
For now we can decrease the version of reqwest so it will use Tokio 0.2
