### ISSUE TITLE
Volume not detected

### ISSUE THREAD

**Issue by skhalymon** [ALLATRA-IT/ephyr#64]
On DigitalOcen and Hetzner we've had an issue with attached volume to the server. The Ephyr saves recorded file in root directory instead of volume. 

We've added volume during installation so installation script should detect the volume.

**Comment by skhalymon** [comment]
I've added logs into places where actual file URL is creating
```
INFO dvr:: 1 Root Path "/var/www/srs/dvr"
INFO dvr:: 2 After trimm "/var/www/srs/dvr/b2efdcac-f16b-40e4-b2fe-8c5f40c7f56f/some.flv"
INFO dvr:: 3 URL Ok(Url { scheme: "file", username: "", password: None, host: None, port: None, path: "/var/www/srs/dvr/b2efdcac-f16b-40e4-b2fe-8c5f40c7f56f/some.flv", query: None, fragment: None })
INFO ffmpeg:: 5 Dst url Url { scheme: "file", username: "", password: None, host: None, port: None, path: "/var/www/srs/dvr/b2efdcac-f16b-40e4-b2fe-8c5f40c7f56f/some.flv", query: None, fragment: None }
```

Interesting that we have currect path for file in variables: `/var/www/srs/dvr/b2efdcac-f16b-40e4-b2fe-8c5f40c7f56f/some.flv`. But the actual file is saving into root `/dvr` folder. Really strange

**Comment by iAnanich** [comment]
Maybe issue is common to VPS volume implementation and happens on lower level? Does it occure locally, on bare-metal unix machines?

**Comment by skhalymon** [comment]
I've reproduced this issue. Info in logs are not really useful, because it shows paths **inside** container. We cannot see the actual path of file system. Inside container we would see always the same path. 

Now I'm checking that's why EPHYR_WWW_DIR is set to blank during execution of provision script.

Also it's a question how to display (https://github.com/ALLATRA-IT/ephyr/issues/34) actual path on the site if it not possible to get it.
