### ISSUE TITLE
Add posibility to add config during instalation of Ephy

### ISSUE THREAD

**Issue by skhalymon** [ALLATRA-IT/ephyr#66]

**Comment by iAnanich** [comment]
So, it requires changes to the installation script that is passed to the server in user-data to accept environment variable with JSON and save it to `state.json`

**Comment by iAnanich** [comment]
This heavily relies on idea from #73 because config might have sensitive data (like RTMP URLs)

**Comment by skhalymon** [comment]
Probably all of this isn't relevant anymore for now?

**Comment by iAnanich** [comment]
Yes. main ptoblem with idea of setting up Ephyr server with config provided at startup is that it requires hosts to be known for each URL used in config.
