### ISSUE TITLE
custom label for each input

### ISSUE THREAD

**Issue by iAnanich** [ALLATRA-IT/ephyr#69]
For each input (including 2 failover ones) of the single block add text label that will accept any text (non-ascii characters, numbers, spaces etc)

![image](https://user-images.githubusercontent.com/1163493/119397804-541f5300-bcdf-11eb-91a0-b243c6503f68.png)

**Comment by PavelKushnirchuk** [comment]
must have ******Х*** nice to have

**Comment by iAnanich** [comment]
This opens opportunity to store and siplay more information aside from putting it inside RTMP URL itself. As of now, URL's location(RestreamKey) and key (InputKey) are pretty limited in size and chars allowed.

**Comment by skhalymon** [comment]
@iAnanich is it relevant?

**Comment by iAnanich** [comment]
> @iAnanich is it relevant?

I still think it is. This change won't require structural manipulations - Ephyr already has FailoverInput objects. So it's just a new field for them and a small change in UI.
Main benefit is that user can write comments here about how they use each input without changing stream key (which isn't editable in web UI).
