### ISSUE TITLE
JSON config - add boolean "muted" field for mixin output

### ISSUE THREAD

**Issue by iAnanich** [ALLATRA-IT/ephyr#72]
At the moment (v0.3.0) JSON config (state.json) does not indicate if mixin output is muted or not - it simply drops value to zero percent, while in the web UI user can mute mixin output and unmute it back without losing original volume (once its unmuted).

**Comment by skhalymon** [comment]
In addition to this issue, we could fix reset volume values after the Edit of output.

**Comment by PavelKushnirchuk** [comment]
Assigned to Andrew

**Comment by deiwo** [comment]
Is there any progress on this issue? I am working on the reset of volumes after edit issue and I can easily fix this one too.
@skhalymon
