### ISSUE TITLE
Idea for URL copy button

### ISSUE THREAD

**Issue by digest0r** [ALLATRA-IT/ephyr#74]
Hello, the current behavior (double click) to copy the URL is quite non-intuitive. Especially when you use double-click text highlighting. I would suggest something like this. It is commonly used approach:

https://user-images.githubusercontent.com/34660048/119658834-df0e6380-be2d-11eb-9b12-c9e068895787.mp4

There is also redundant white space in the beginning of the URL block which is accidentally being copied as well:
![ephyr-url-space-before](https://user-images.githubusercontent.com/34660048/119659088-1f6de180-be2e-11eb-8ac7-09e2c2e7e82c.png)

I could help with these if it makes sense to implement it

**Comment by PavelKushnirchuk** [comment]
@digest0r I think it makes sense). You can try to implement it of cause.

**Comment by skhalymon** [comment]
Implementet in https://github.com/ALLATRA-IT/ephyr/pull/76
