### ISSUE TITLE
Proposal: rename Restream's input keys

### ISSUE THREAD

**Issue by iAnanich** [ALLATRA-IT/ephyr#89]
Idea is to make *main* key (served as pull/push without failover inputs) to be explicitly named "main", and add more clarity to failover input keys renaming them to "inject" (or input) and "fallback" (or "secondary").

Ideally, from the user's perspective, the behavior of "origin" (as it is called now) should not change when the user wants to add backup input. It has to always be only for push, with one failover input serving as a single push endpoint. Their "keys" can stay the same, but when the user wants to add backup input, and key of backup input will be different.

**Comment by skhalymon** [comment]
@iAnanich what do you think if rename `main` to `primary` and backup leave as is?

**Comment by iAnanich** [comment]
Good too
